version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - "data:/data/db"
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    command: node app.js
    volumes:
      - models:/app/models
      - ./backend/app:/app/backend/app  
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
volumes:
  data:
  models: